package com.synapse.backend.shared.validation;

/**
 * The single source of every length and range limit that request DTOs validate against.
 *
 * <p>A limit lives here rather than as a literal on the field so that the endpoint which
 * creates a value and the endpoint which later edits that same value cannot drift apart:
 * both reference the same constant, and changing a limit changes both at once.</p>
 *
 * <p>Values that a user never types are bounded too. Titles and body text generated by the
 * LLM are clamped to these same limits before they are persisted, so a generated note can
 * always be saved again through its own edit endpoint without being shortened first.</p>
 */
public final class ValidationLimits {

    /** RFC 5321's maximum address length, and what {@code users.email} stores. */
    public static final int EMAIL_MAX = 254;

    /** NIST SP 800-63B's recommended minimum secret length. */
    public static final int PASSWORD_MIN = 8;

    /** Upper bound on a password in characters. */
    public static final int PASSWORD_MAX = 64;

    /**
     * Upper bound on a password in UTF-8 bytes. BCrypt refuses to hash a secret longer than
     * this, so a password that passes {@link #PASSWORD_MAX} but not this one would fail
     * inside the encoder rather than in validation.
     */
    public static final int PASSWORD_MAX_BYTES = 72;

    /** Minimum length of a person's full name. */
    public static final int FULL_NAME_MIN = 2;

    /** Maximum length of a person's full name, matching {@code users.full_name}. */
    public static final int FULL_NAME_MAX = 100;

    /** Maximum length of an IANA time zone identifier, matching {@code users.time_zone}. */
    public static final int TIME_ZONE_MAX = 64;

    /** Maximum length of an opaque emailed token. */
    public static final int TOKEN_MAX = 255;

    /** Length of the nanoid public identifier every resource is addressed by. */
    public static final int PUBLIC_ID_MAX = 10;

    /** Maximum length of any user-facing title or name of a piece of content. */
    public static final int TITLE_MAX = 200;

    /** Maximum length of a short description attached to a quiz or a group. */
    public static final int DESCRIPTION_MAX = 500;

    /** Maximum length of a note's summary body. */
    public static final int OVERVIEW_MAX = 5000;

    /** Maximum length of one side of a flashcard. */
    public static final int FLASHCARD_TEXT_MAX = 1000;

    /** Maximum length of a quiz question's text. */
    public static final int QUESTION_TEXT_MAX = 1000;

    /** Maximum length of one of a question's answer options. */
    public static final int ANSWER_TEXT_MAX = 500;

    /** Maximum length of the search term on a list endpoint. */
    public static final int SEARCH_QUERY_MAX = 100;

    /** Longest study session that can be reported, in seconds. Six hours. */
    public static final int DURATION_SECONDS_MAX = 21600;

    /** Lowest quiz difficulty. */
    public static final int DIFFICULTY_MIN = 1;

    /** Highest quiz difficulty. */
    public static final int DIFFICULTY_MAX = 5;

    /** Largest page a list endpoint will return. */
    public static final int PAGE_SIZE_MAX = 100;

    /** Smallest page a list endpoint will return. */
    public static final int PAGE_SIZE_MIN = 1;

    private ValidationLimits() {
    }

}
